### ISSUE TITLE
Implement Jazzband guidelines for project inflect.py

### ISSUE THREAD

**Issue by jazzband-bot** [jazzband/inflect#80]
This issue tracks the implementation of the [Jazzband guidelines](https://jazzband.co/about/guidelines) for the project [inflect.py](https://github.com/jazzband/inflect.py)

It was initiated by @jaraco who was automatically assigned in addition to the [Jazzband roadies](https://jazzband.co/roadies).

See the [TODO list](#todos) below for the generally required tasks, but feel free to update it in case the project requires it.

Feel free to ping a [Jazzband roadie](https://jazzband.co/roadies) if you have any question.

## TODOs<a name="todos"></a>

- [x] Fix all links in the docs (and README file etc) from old to new repo
- [x] Add the [Jazzband badge](https://jazzband.co/about/guidelines#badges) to the `README` file
- [x] Add the [Jazzband contributing guideline](https://jazzband.co/about/guidelines#contributing-guidelines) to the `CONTRIBUTING.md` file
- [x] Check if continuous testing works (e.g. [Travis-CI](https://travis-ci.org/), [CircleCI](https://circleci.com), [AppVeyor](https://www.appveyor.com), etc)
- [x] Check if test coverage services work (e.g. [Coveralls](https://coveralls.io), [Codecov](https://codecov.io), etc)
- [x] Add `jazzband` account to [PyPI](https://pypi.python.org/) project as maintainer role (URL: `https://pypi.python.org/pypi?:action=role_form&package_name=<PROJECTNAME>`)
- [x] Add `jazzband-bot` as maintainer to the [Read the Docs](https://readthedocs.org/) project (URL: `https://readthedocs.org/dashboard/<PROJECTNAME>/users/`)
- [x] Fix project URL in [GitHub project](https://github.com/jazzband/inflect.py) description
- [x] Review project if other services are used and port them to Jazzband

## Project details

<table>
  <caption></caption>
  <tr>
    <td>Description</td>
    <td>Correctly generate plurals, ordinals, indefinite articles; convert numbers to words</td>
  </tr>
  <tr>
    <td>Homepage</td>
    <td>http://pypi.python.org/pypi/inflect</td>
  </tr>
  <tr>
    <td>Stargazers</td>
    <td>0</td>
  </tr>
  <tr>
    <td>Open issues</td>
    <td>0</td>
  </tr>
  <tr>
    <td>Forks</td>
    <td>0</td>
  </tr>
  <tr>
    <td>Default branch</td>
    <td>master</td>
  </tr>
  <tr>
    <td>Is a fork</td>
    <td>True</td>
  </tr>
  <tr>
    <td>Has Wiki</td>
    <td>True</td>
  </tr>
  <tr>
    <td>Has Pages</td>
    <td>False</td>
  </tr>
</table>

**Comment by jaraco** [comment]
I am yes. And I'm also extremely slow to respond to e-mails. Just let me know what needs to happen next.

**Comment by jezdez** [comment]
@jaraco So it seems you're interested in the release process, sorry it took so long to get back to you. I'll enable the functionality over the course of this week via Travis CI and the Jazzband package index.

**Comment by jezdez** [comment]
FTR, I've closed a related ticket about adding Azure Pipelines in #101 because of the best practices around maintaining the Jazzband release infrastructure. Azure Pipelines are currently not part of that but Travis is.

**Comment by jaraco** [comment]
This project is going to use the lightweight, Github Actions technique as adopted by other projects deriving from [jaraco/skeleton](/jaraco/skeleton).

**Comment by jezdez** [comment]
@jaraco That's good to know since I think we'll need to port all of the Jazzband projects to Github Actions this year before travis-ci.org shuts down, too.
